version: '3.8'

services:
  vault:
    image: vault
    volumes:
      - $PWD/logs/:/tmp/logs
      - ./vault:/scripts
    cap_add:
      - IPC_LOCK
    # mounted from the ./vault folder
    command: /scripts/vault.sh
    ports:
      - 8200:8200
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: testing-token
      VAULT_ADDR: http://0.0.0.0:8200
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200

  mongodb:
    image: 'bitnami/mongodb:4.0'
    ports:
      - '27027:27017'
    volumes:
      - 'mongodb_data:/bitnami'
    environment:
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: password
      MONGODB_DATABASE: appdb
      MONGODB_ROOT_PASSWORD: password123

  object-storage:
    image: minio/minio
    container_name: object-storage
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    ports:
      - "8085:9000"

  # for email services
  mailhog:
    image: mailhog/mailhog
    container_name: 'mailhog'
    ports:
      - "1025:1025"
      - "8025:8025"      

  nginx:
    build:
      context: ./nginx
    ports:
      - "9090:8080"

  server:
    build: 
      context: ../
    depends_on:
      - mongodb
    environment:
      NODE_ENV: development
      EMAIL_HOST: mailhog
      EMAIL_PORT: 1025
      AUTH_ENABLED: "true"
      BASE_PATH: /
      VAULT_ENABLED: "false"
      DB_URL: mongodb://mongodb:27017/appdb
      DB_NAME: appdb
      DB_USERNAME: admin
      DB_PASSWORD: password
      OBJECT_STORAGE_ENDPOINT: http://object-storage:9000/
      OBJECT_STORAGE_BUCKET: daco-dev
      OBJECT_STORAGE_KEY: minio
      OBJECT_STORAGE_SECRET: minio123
      PORT: 3001
    ports:
      - "3001:3001"

volumes:
  mongodb_data:
    name: appdb_db_vol_1
    driver: local
