services:
  vault:
    image: vault:1.13.3
    volumes:
      - $PWD/logs/:/tmp/logs
      - ./vault:/scripts
    cap_add:
      - IPC_LOCK
    # mounted from the ./vault folder
    command: /scripts/vault.sh
    ports:
      - 8200:8200
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: testing-token
      VAULT_ADDR: http://0.0.0.0:8200
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200

  # local replica setup modified from https://github.com/bitnami/containers/blob/main/bitnami/mongodb/docker-compose-replicaset.yml
  mongodb:
    image: 'bitnami/mongodb:4.0'
    ports:
      - '27027:27017'
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=password
      - MONGODB_DATABASE=appdb
    volumes:
      - 'mongodb_data:/bitnami'

  object-storage:
    image: minio/minio
    container_name: object-storage
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    ports:
      - '8085:9000'
    volumes:
      - 'minio_data:/data'

  # for email services
  mailhog:
    image: jcalonso/mailhog:latest
    container_name: mailhog
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
  mongodb_data:
    name: appdb_db_vol_1
    driver: local
  minio_data:
