version: '3.8'

services:
  vault:
    image: vault
    volumes:
      - $PWD/logs/:/tmp/logs
      - ./vault:/scripts
    cap_add:
      - IPC_LOCK
    # mounted from the ./vault folder
    command: /scripts/vault.sh
    ports:
      - 8200:8200
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: testing-token
      VAULT_ADDR: http://0.0.0.0:8200
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200

  mongodb:
    image: 'bitnami/mongodb:4.0'
    ports:
      - '27027:27017'
    volumes:
      - 'mongodb_data:/bitnami'
    environment:
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: password
      MONGODB_DATABASE: appdb
      MONGODB_ROOT_PASSWORD: password123

  object-storage:
    image: minio/minio
    container_name: object-storage
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    ports:
      - "8085:9000"

  # for email services
  mailhog:
    image: mailhog/mailhog
    container_name: 'mailhog'
    ports:
      - "1025:1025"
      - "8025:8025"      

volumes:
  mongodb_data:
    name: appdb_db_vol_1
    driver: local
